version: "3"
services:
  service_a:
    container_name: nginx_pgsql_basic_example_service_a
    build:
      dockerfile: ./Dockerfile.serviceA
      context: .
    image: janisis.azurecr.io/servicea
    ports:
      - 3000:3000
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_DATABASE: $PG_DB
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      - nginx-pgsql-basic-example
    depends_on:
      - postgres
  service_b:
    container_name: nginx_pgsql_basic_example_service_b
    build:
      dockerfile: ./Dockerfile.serviceB
      context: .
    image: janisis.azurecr.io/serviceb
    ports:
      - 3001:3000
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_DATABASE: $PG_DB
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      - nginx-pgsql-basic-example
    depends_on:
      - postgres
  postgres:
    container_name: nginx_pgsql_basic_example_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB
    networks:
      - nginx-pgsql-basic-example
    volumes:
      - nginx-pgsql-basic-example:/var/lib/postgresql/data

networks:
  nginx-pgsql-basic-example:
volumes:
  nginx-pgsql-basic-example: