apiVersion: v1
kind: Secret
metadata:
  name: dbinfo
  namespace: ingress-example
type: Opaque
stringData:
    PG_HOST: postgres
    PG_USER: janisis
    PG_PASSWORD: supersecret 
    PG_DATABASE: janisis